name: jupyter_demos
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.7
  - beakerx=1.3.0
  - numpy=1.16.2
  - pandas=0.24.2
  - openpyxl=2.6.1
  - tornado=5.1.1


