name: jupyter_demos
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.7
  - numpy=1.16.2
  - beakerx=1.3.0
  - graphviz
  - jupyter
  - matplotlib
  - pandas
  - python-graphviz
  - r-essentials
  - r-irkernel
  - rpy2
  - scikit-learn
  - simplegeneric
  - seaborn
  - tornado=5.1.1
  - tzlocal

