name: jupyter_demos
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beakerx
  - graphviz
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python-graphviz
  - r-irkernel
  - rpy2
  - scikit-learn
  - seaborn
  - tornado
  - tzlocal

