name: jupyter_demos
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beakerx
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - python-graphviz
  - r-irkernel
  - rpy2
  - scikit-learn
  - scipy
  - seaborn
  - tornado<6
