name: jupyter_demos
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beakerx=1.3.0
  - graphviz=2.40.1
  - jupyter=1.0.0
  - matplotlib=3.0.3
  - numpy=1.16.2
  - pandas=0.24.2
  - python-graphviz=0.10.1
  - r-irkernel=0.8.15
  - rpy2=2.9.4
  - scikit-learn=0.20.3
  - seaborn=0.9.0
  - tornado=5.1.1
  - tzlocal

