name: jupyter_demos
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.0
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - beakerx=1.3.0
  - bleach=3.1.0
  - bwidget=1.9.11=1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - cairo=1.16.0
  - cctools=895
  - certifi=2019.3.9
  - cffi=1.12.2
  - chardet=3.0.4
  - clang=4.0.1
  - clang_osx-64=4.0.1
  - clangxx=4.0.1
  - clangxx_osx-64=4.0.1
  - compiler-rt=4.0.1
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - gfortran_osx-64=4.8.5
  - glib=2.58.3
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gsl=2.4
  - harfbuzz=2.3.1
  - icu=58.2
  - idna=2.8
  - ipykernel=5.1.0
  - ipython=7.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - krb5=1.16.3
  - ld64=274.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1=0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.3
  - libpng=1.6.36
  - libsodium=1.0.16
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.8
  - llvm=4.0.1
  - llvm-lto-tapi=4.0.1
  - llvm-openmp=4.0.1
  - make=4.2.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - maven=3.6.0=0
  - mistune=0.8.4
  - more-itertools=4.3.0
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numpy=1.16.2
  - openblas=0.3.5
  - openjdk=11.0.1
  - openssl=1.1.1b
  - pandas=0.24.2
  - pandoc=2.7.1=0
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso=0.3.4
  - patsy=0.5.1
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - pixman=0.34.0
  - pluggy=0.9.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - py=1.8.0
  - py4j=0.10.8.1
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pyrsistent=0.14.11
  - pysocks=1.6.8
  - pytest=4.4.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - python-graphviz=0.10.1
  - pytz=2018.9
  - pyzmq=18.0.1
  - qt=5.6.2
  - qtconsole=4.4.3
  - r-abind=1.4_5
  - r-assertthat=0.2.0
  - r-backports=1.1.2
  - r-base=3.5.1
  - r-base64enc=0.1_3
  - r-bh=1.66.0_1
  - r-bindr=0.1.1
  - r-bindrcpp=0.2.2
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-blob=1.1.1
  - r-boot=1.3_20
  - r-broom=0.5.0
  - r-callr=2.0.4
  - r-caret=6.0_80
  - r-cellranger=1.1.0
  - r-class=7.3_14
  - r-cli=1.0.0
  - r-clipr=0.4.1
  - r-cluster=2.0.7_1
  - r-codetools=0.2_15
  - r-colorspace=1.3_2
  - r-crayon=1.3.4
  - r-curl=3.2
  - r-cvst=0.2_2
  - r-data.table=1.11.4
  - r-dbi=1.0.0
  - r-dbplyr=1.2.2
  - r-ddalpha=1.3.4
  - r-deoptimr=1.0_8
  - r-dichromat=2.0_0
  - r-digest=0.6.15
  - r-dimred=0.1.0
  - r-dplyr=0.7.6
  - r-drr=0.0.3
  - r-essentials=3.5.1
  - r-evaluate=0.11
  - r-fansi=0.2.3
  - r-forcats=0.3.0
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-formatr=1.5
  - r-geometry=0.3_6
  - r-ggplot2=3.0.0
  - r-glmnet=2.0_16
  - r-glue=1.3.0
  - r-gower=0.1.2
  - r-gtable=0.2.0
  - r-haven=1.1.2
  - r-hexbin=1.27.2
  - r-highr=0.7
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.2
  - r-httpuv=1.4.5
  - r-httr=1.3.1
  - r-ipred=0.9_6
  - r-irdisplay=0.5.0
  - r-irkernel=0.8.15
  - r-iterators=1.0.10
  - r-jsonlite=1.5
  - r-kernlab=0.9_26
  - r-kernsmooth=2.23_15
  - r-knitr=1.20
  - r-labeling=0.3
  - r-later=0.7.3
  - r-lattice=0.20_35
  - r-lava=1.6.2
  - r-lazyeval=0.2.1
  - r-lubridate=1.7.4
  - r-magic=1.5_8
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=0.8
  - r-mass=7.3_50
  - r-matrix=1.2_14
  - r-memoise=1.1.0
  - r-mgcv=1.8_24
  - r-mime=0.5
  - r-modelmetrics=1.1.0
  - r-modelr=0.1.2
  - r-munsell=0.5.0
  - r-nlme=3.1_137
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1
  - r-openssl=1.0.2
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.0
  - r-pkgconfig=2.0.1
  - r-plogr=0.2.0
  - r-pls=2.6_0
  - r-plyr=1.8.4
  - r-praise=1.0.0
  - r-prettyunits=1.0.2
  - r-processx=3.1.0
  - r-prodlim=2018.04.18
  - r-promises=1.0.1
  - r-purrr=0.2.5
  - r-quantmod=0.4_13
  - r-r6=2.2.2
  - r-randomforest=4.6_14
  - r-rbokeh=0.6.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=0.12.18
  - r-rcpproll=0.3.0
  - r-readr=1.1.1
  - r-readxl=1.1.0
  - r-recipes=0.1.3
  - r-recommended=3.5.1
  - r-rematch=1.0.1
  - r-repr=0.15.0
  - r-reprex=0.2.0
  - r-reshape2=1.4.3
  - r-rlang=0.2.1
  - r-rmarkdown=1.10
  - r-robustbase=0.93_2
  - r-rpart=4.1_13
  - r-rprojroot=1.3_2
  - r-rsqlite=2.1.1
  - r-rstudioapi=0.7
  - r-rvest=0.3.2
  - r-scales=0.5.0
  - r-selectr=0.4_1
  - r-sfsmisc=1.1_2
  - r-shiny=1.1.0
  - r-sourcetools=0.1.7
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringi=1.2.4
  - r-stringr=1.3.1
  - r-survival=2.42_6
  - r-testthat=2.0.0
  - r-tibble=1.4.2
  - r-tidyr=0.8.1
  - r-tidyselect=0.2.4
  - r-tidyverse=1.2.1
  - r-timedate=3043.102
  - r-tinytex=0.6
  - r-ttr=0.23_3
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.3
  - r-xml2=1.2.0
  - r-xtable=1.8_2
  - r-xts=0.11_0
  - r-yaml=2.2.0
  - r-zoo=1.8_3
  - readline=7.0
  - requests=2.21.0
  - rpy2=2.9.4
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tktable=2.10
  - tornado=5.1.1
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11

